version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "07:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
