HIGH_PROBABILITY = 80
MEDIUM_PROBABILITY = 55

HIGH_CONFIDENCE_MIN_MEMORIES = 20
MEDIUM_CONFIDENCE_MIN_MEMORIES = 5

LOW_RISK = "LOW"
MEDIUM_RISK = "MEDIUM"
HIGH_RISK = "HIGH"

RECOMMEND_PRODUCE = "PRODUCIR"
RECOMMEND_CAREFUL = "PRODUCIR_CON_CUIDADO"
RECOMMEND_SKIP = "NO_PRIORIZAR"